#!/usr/bin/env bash
# Install Xray Control as a systemd service on Debian/Ubuntu-like systems.
set -Eeuo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "این اسکریپت را با sudo یا کاربر root اجرا کنید." >&2
  exit 1
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/panel}"
DATA_DIR="${DATA_DIR:-/var/lib/xray-panel}"
ENV_DIR="/etc/xray-panel"
ENV_FILE="${ENV_DIR}/panel.env"
ADMIN_USER="${ADMIN_USERNAME:-admin}"
ADMIN_PASS="${ADMIN_PASSWORD:-admin123}"

if [[ "${#ADMIN_PASS}" -lt 8 ]]; then
  echo "کلمه عبور مدیر باید حداقل ۸ کاراکتر باشد." >&2
  exit 1
fi

if command -v apt-get >/dev/null 2>&1; then
  echo "[1/6] نصب پیش‌نیازهای سیستم…"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y python3 python3-venv python3-pip ca-certificates curl openssl rsync
else
  echo "هشدار: apt-get پیدا نشد؛ پیش‌نیازها را دستی بررسی کنید."
fi

echo "[2/6] کپی فایل‌های پنل به ${INSTALL_DIR}…"
mkdir -p "${INSTALL_DIR}" "${DATA_DIR}" "${ENV_DIR}"
# rsync avoids copying the repository's .git folder and local databases.
rsync -a --delete \
  --exclude '.git/' \
  --exclude 'panel.db' \
  --exclude 'core/config.json' \
  --exclude '__pycache__/' \
  --exclude 'venv/' \
  --exclude '.venv/' \
  "${PROJECT_DIR}/" "${INSTALL_DIR}/"

# Keep the database and generated config outside the application tree.
JWT_SECRET="${JWT_SECRET_KEY:-}"
if [[ -z "${JWT_SECRET}" ]]; then
  JWT_SECRET="$(openssl rand -hex 32)"
fi

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/install.sh. Permissions are intentionally restrictive.
DATABASE_URL=sqlite:////var/lib/xray-panel/panel.db
XRAY_CONFIG_PATH=/etc/xray/config.json
XRAY_RELOAD_COMMAND=systemctl reload xray
JWT_SECRET_KEY=${JWT_SECRET}
ADMIN_USERNAME=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASS}
ENABLE_PUBLIC_IP_LOOKUP=${ENABLE_PUBLIC_IP_LOOKUP:-0}
CORS_ORIGINS=${CORS_ORIGINS:-*}
EOF
chmod 600 "${ENV_FILE}"

if [[ ! -d "${INSTALL_DIR}/venv" ]]; then
  echo "[3/6] ساخت محیط مجازی Python…"
  python3 -m venv "${INSTALL_DIR}/venv"
fi
"${INSTALL_DIR}/venv/bin/pip" install --upgrade pip
"${INSTALL_DIR}/venv/bin/pip" install -r "${INSTALL_DIR}/requirements.txt"

if [[ "${INSTALL_XRAY:-1}" == "1" ]] && ! command -v xray >/dev/null 2>&1; then
  echo "[4/6] نصب Xray-core…"
  XRAY_INSTALLER_URL="${XRAY_INSTALLER_URL:-https://github.com/XTLS/Xray-install/raw/main/install-release.sh}"
  curl --fail --location --proto '=https' --tlsv1.2 "${XRAY_INSTALLER_URL}" | bash -s -- install
else
  echo "[4/6] نصب Xray-core رد شد یا از قبل نصب است."
fi

# The service template opts into a reload after each config mutation. A
# missing xray service is harmless because the generated JSON remains on disk.
echo "[5/6] فعال‌سازی سرویس systemd…"
install -m 0644 "${INSTALL_DIR}/systemd/panel.service" /etc/systemd/system/xray-panel.service
mkdir -p /etc/xray
systemctl daemon-reload
systemctl enable xray-panel.service
systemctl restart xray-panel.service

# Wait briefly for a health response, but don't turn a successful install into
# a failure on machines where a local firewall blocks loopback probing.
echo "[6/6] بررسی سلامت پنل…"
for _ in {1..10}; do
  if curl --silent --fail http://127.0.0.1:8000/health >/dev/null; then break; fi
  sleep 1
done

cat <<EOF

===============================================
نصب Xray Control با موفقیت انجام شد.
آدرس پنل: http://<SERVER-IP>:8000
نام کاربری: ${ADMIN_USER}
کلمه عبور: ${ADMIN_PASS}
فایل تنظیمات محیطی: ${ENV_FILE}
دیتابیس: ${DATA_DIR}/panel.db
===============================================
هشدار: کلمه عبور پیش‌فرض را از داخل پنل تغییر دهید و پورت ۸۰۰۰ را پشت HTTPS/reverse proxy قرار دهید.
برای نصب بدون Xray از INSTALL_XRAY=0 استفاده کنید.
EOF
